apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d10y9tgpj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d10y9tgpj-nodejs 
  name: d10y9tgpj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: d10y9tgpj-nodejs 
